# Generated by Django 5.1.4 on 2025-02-22 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_full_name', models.CharField(max_length=32)),
                ('admin_picture', models.FileField(upload_to='admin_picture')),
                ('job_title', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_image', models.FileField(upload_to='school_images')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='School_timeline',
            new_name='Timeline',
        ),
        migrations.DeleteModel(
            name='Administration',
        ),
        migrations.DeleteModel(
            name='School_gallery',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_name',
            new_name='teacher_full_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='telegram',
        ),
        migrations.AddField(
            model_name='communication',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communication',
            name='telegram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
        migrations.AddField(
            model_name='admin',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.specialization'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.specialization'),
        ),
    ]
