# Generated by Django 5.1.4 on 2025-03-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_admin_gallery_specialization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
